In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_excel("C:/Users/carefree671/Desktop/模型库/单胞/atoms.xlsx")

In [5]:
coordinate = pd.DataFrame(data, columns=['x', 'y', 'z'])

In [6]:
coordinate

x          y          z
0     8.511363  10.227518   8.511602
1     9.663229   9.663426   7.945909
2    10.227441   8.511503   8.511368
3     9.663300   7.945929   9.663330
4     8.511325   8.511388  10.227535
..         ...        ...        ...
619   4.708875   4.709040  10.227563
620   3.556982   5.274471   9.663177
621   3.110737   3.109918   7.050015
622   6.170608   3.110615  10.110446
623   3.110106   6.170366  10.109792

[624 rows x 3 columns]

In [7]:
coord = np.array(coordinate)

In [8]:
coord

array([[ 8.511363, 10.227518,  8.511602],
       [ 9.663229,  9.663426,  7.945909],
       [10.227441,  8.511503,  8.511368],
       ...,
       [ 3.110737,  3.109918,  7.050015],
       [ 6.170608,  3.110615, 10.110446],
       [ 3.110106,  6.170366, 10.109792]])

In [9]:
Q = np.array([[(2**0.5)/2, -(2**0.5)/2, 0],
              [(2**0.5)/2, (2**0.5)/2, 0],
              [0, 0, 1]])

In [11]:
T_coord = coord.T

In [12]:
T_coord

array([[ 8.511363,  9.663229, 10.227441, ...,  3.110737,  6.170608,
         3.110106],
       [10.227518,  9.663426,  8.511503, ...,  3.109918,  3.110615,
         6.170366],
       [ 8.511602,  7.945909,  8.511368, ...,  7.050015, 10.110446,
        10.109792]])

In [13]:
change_coord = np.dot(Q, T_coord)

In [16]:
change_coord_data = pd.DataFrame(change_coord.T)

In [17]:
change_coord_data.to_excel("C:/Users/carefree671/Desktop/模型库/单胞/转换坐标.xlsx")

In [24]:
box_coordinate = np.array([[0, 0 ,0],
                           [26.4408, 26.4408 ,26.4408]])

In [25]:
change_box = np.dot(Q, box_coordinate.T)

In [26]:
change_box

array([[ 0.        ,  0.        ],
       [ 0.        , 37.39293796],
       [ 0.        , 26.4408    ]])

In [27]:
change_box_coord = pd.DataFrame(change_box.T)

In [28]:
change_box_coord

0          1        2
0  0.0   0.000000   0.0000
1  0.0  37.392938  26.4408